title: hijos-de-puta records
email: elgusanorojo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hijos de Puta records
baseurl: "/site"
url: "http://hijos-de-puta.org"
exclude: [vendor]
